apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-firebase
type: Opaque
{{- if contains "dev" .Values.env }}
data:
  firebase.json: |-
    {{ .Files.Get "firebase-prod.json" | b64enc }}
{{- end }}
{{- if contains "prod" .Values.env }}
data:
  firebase.json: |-
    {{ .Files.Get "firebase-prod.json" | b64enc }}
{{- end }}